# Generated by Django 5.2.17 on 2026-10-02 05:15

import django.db.models.deletion
import wagtail.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0098_apitoken'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.WAGTAIL_PAGE_MODEL)),
            ],
            options={
                'verbose_name': '文章目录',
                'verbose_name_plural': '文章目录',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ArticlePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.WAGTAIL_PAGE_MODEL)),
                ('summary', models.CharField(help_text='用于文章列表和文章简介，不超过 300 个字符。', max_length=300, verbose_name='摘要')),
                ('cover_alt', models.CharField(blank=True, help_text='描述封面内容；纯装饰性封面可以留空。', max_length=200, verbose_name='封面替代文本')),
                ('body', wagtail.fields.StreamField([('heading', 2), ('paragraph', 3), ('image', 6), ('quote', 9), ('code', 12)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': '标题文字', 'max_length': 200}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('h2', '二级标题'), ('h3', '三级标题')], 'label': '标题级别'}), 2: ('wagtail.blocks.StructBlock', [[('text', 0), ('level', 1)]], {}), 3: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ol', 'ul'], 'label': '段落'}), 4: ('wagtail.images.blocks.ImageBlock', [], {'label': '图片'}), 5: ('wagtail.blocks.CharBlock', (), {'label': '图注', 'max_length': 300, 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('image', 4), ('caption', 5)]], {}), 7: ('wagtail.blocks.TextBlock', (), {'label': '引用内容'}), 8: ('wagtail.blocks.CharBlock', (), {'label': '来源', 'max_length': 200, 'required': False}), 9: ('wagtail.blocks.StructBlock', [[('text', 7), ('source', 8)]], {}), 10: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('text', '纯文本'), ('python', 'Python'), ('javascript', 'JavaScript'), ('typescript', 'TypeScript'), ('html', 'HTML'), ('css', 'CSS'), ('bash', 'Bash'), ('sql', 'SQL'), ('json', 'JSON')], 'label': '语言'}), 11: ('wagtail.blocks.TextBlock', (), {'label': '代码'}), 12: ('wagtail.blocks.StructBlock', [[('language', 10), ('code', 11)]], {})}, verbose_name='正文')),
                ('cover_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='封面图')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
            },
            bases=('wagtailcore.page',),
        ),
    ]
