"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

import environ


BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env()
env_file = BASE_DIR / ".env"

if env_file.is_file():
    environ.Env.read_env(env_file)

SECRET_KEY = env.str("DJANGO_SECRET_KEY")
DEBUG = env.bool("DJANGO_DEBUG", default=False)
ALLOWED_HOSTS = env.list("DJANGO_ALLOWED_HOSTS")


# Application definition

INSTALLED_APPS = [
    "wagtail.api.v2",
    "articles.apps.ArticlesConfig",

    # Wagtail 内容管理组件
    "wagtail.embeds",
    "wagtail.sites",
    "wagtail.users",
    "wagtail.snippets",
    "wagtail.documents",
    "wagtail.images",
    "wagtail.search",
    "wagtail.admin",
    "wagtail",

    # Wagtail 使用的配套组件
    "modelcluster",
    "taggit",
    "django_filters",

    # Django 基础组件
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": env.str("POSTGRES_DB"),
        "USER": env.str("POSTGRES_USER"),
        "PASSWORD": os.environ["POSTGRES_PASSWORD"],
        "HOST": env.str("POSTGRES_HOST"),
        "PORT": env.int("POSTGRES_PORT"),
        "CONN_MAX_AGE": 0 if DEBUG else 60,
        "CONN_HEALTH_CHECKS": True,
        "OPTIONS": {
            "connect_timeout": 10,
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# Wagtail 后台使用的 CSS、JavaScript、图标
STATIC_URL = "/cms-static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

# 上传的封面、正文图片和附件
MEDIA_URL = "/cms-media/"
MEDIA_ROOT = Path(
    env.str("CMS_MEDIA_ROOT", default=str(BASE_DIR / "media"))
)

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Wagtail 后台显示的站点名称
WAGTAIL_SITE_NAME = "Banyan"

# 后台生成完整链接时使用的服务地址
WAGTAILADMIN_BASE_URL = env.str("CMS_BASE_URL")

# 允许复杂文章编辑表单包含更多字段
DATA_UPLOAD_MAX_NUMBER_FIELDS = 10_000

# API 生成完整链接时使用的后端地址
WAGTAILAPI_BASE_URL = env.str("CMS_BASE_URL").rstrip("/")

# 单次列表请求最多返回 50 篇文章
WAGTAILAPI_LIMIT_MAX = 50

# 文章网页所在的前端地址
FRONTEND_BASE_URL = env.str("FRONTEND_BASE_URL").rstrip("/")

# API 中的富文本输出为浏览器可显示的 HTML
WAGTAILAPI_RICH_TEXT_FORMAT = "html"

# 仅在生产环境启用
if not DEBUG:
    # 公网 HTTPS 由 Nginx 处理，Django 通过该请求头识别
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

    # 登录会话与 CSRF Cookie 只通过 HTTPS 发送
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

    # 上传文件供后端账号和 Nginx 读取
    FILE_UPLOAD_PERMISSIONS = 0o640
    FILE_UPLOAD_DIRECTORY_PERMISSIONS = 0o2750